var student=[
		{
			name:"vimal",
			age:22,
			gender:"male",
			result:"pass"
		},
		{
			name:"sabari",
			age:21,
			gender:"male",
			result:"pass"
		},
		{
			name:"anju",
			age:22,
			gender:"female",
			result:"pass"
		},
		{
			name:"srikaanth",
			age:22,
			gender:"male",
			result:"pass"
		},
		{
			name:"sathish",
			age:22,
			gender:"male",
			result:"fail"
		}]
for (var i =0; i <= 4; i++) 
	{
		console.log(student[i].name);
		console.log(student[i].result);
	}
student.forEach(
		function(i,e)
		{
			console.log(i.name);
			console.log(i.result);
			
		}
	)